apiVersion: apps/v1
kind: Deployment
metadata:
  name: parth-spring-kotlin
spec:
  selector:
    matchLabels:
      app: parth-spring-kotlin
  template:
    metadata:
      labels:
        app: parth-spring-kotlin
    spec:
      containers:
      - name: parth-spring-kotlin
        image: piomin/parth-spring-kotlin:1.4.8
        ports:
        - containerPort: 8080
          name: http